In [2]:
import numpy as np

In [3]:
#step 6
A = np.array([[5, 1, -2, 0], [0, 3, 4, 3], [2, 3, 1, 1]])
B = np.array([[1, -3], [2, -2], [3, -1], [0, 0]])
C = A.dot(B)
print(C.sum())

-8


In [5]:
#step 7
def no_numpy_mult(first, second):
    result = [[0] * len(second[0]) for i in range(len(first))]
    for k in range(len(first)):
        for t in range(len(second[0])):
            temp = 0
            for i, j in zip(range(len(first[0])), range(len(second))):
                temp += first[k][i] * second[j][t]
            result[k][t] = temp

    return result

def numpy_mult(first, second):

    return first.dot(second)      

In [6]:
#step 8
def no_numpy_scalar(v1, v2):
    return sum(list([i*j for i, j in zip(v1, v2)]))

def numpy_scalar(v1, v2):
    return v1.dot(v2)

In [7]:
def diag_2k(a):
    b = np.diag(a)
    b = b[b % 2 == 0]
    return np.sum(b)
a = [[i for i in range(5)] for j in range(5)]
a = np.array(a)
diag_2k(a)

6

In [8]:
#step 10
def cumsum(A):
    res = np.cumsum(A, axis=1)
    return res
a, cumsum(a)

    

(array([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]]),
 array([[ 0,  1,  3,  6, 10],
        [ 0,  1,  3,  6, 10],
        [ 0,  1,  3,  6, 10],
        [ 0,  1,  3,  6, 10],
        [ 0,  1,  3,  6, 10]]))

In [9]:
#step 11
def transform(X, a=1):
    T1 = X[:,::2]**3
    T2 = np.where(X[:,1::2], a, 0)
    T3 = np.zeros(shape=X.shape, dtype=X.dtype)
    T3[:,::2] = T1[:,:]
    T3[:,1::2] = T2[:, :]
    T3[:, :] = T3[:, ::-1]
    result = np.hstack([X, T3])
    return result

b = transform(a)
b

array([[ 0,  1,  2,  3,  4, 64,  1,  8,  1,  0],
       [ 0,  1,  2,  3,  4, 64,  1,  8,  1,  0],
       [ 0,  1,  2,  3,  4, 64,  1,  8,  1,  0],
       [ 0,  1,  2,  3,  4, 64,  1,  8,  1,  0],
       [ 0,  1,  2,  3,  4, 64,  1,  8,  1,  0]])

In [12]:
#step 12 решение говно, конечно
def encode(a):
    elements = []
    counts = []
    temp = a[0]
    count = 0
    for i in a:
        if temp == i:
            count += 1
        else:
            elements.append(temp)
            counts.append(count)
            count = 1
            temp = i
    elements.append(temp)
    counts.append(count)        
    return (elements, counts)        

X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
c = encode(X)
c


([1, 2, 3, 1, 5, 2, 3], [1, 2, 2, 2, 2, 1, 2])